server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    #=========== Log ============
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    #=========== Laravel routing ============
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    #========== PHP-FPM configuration ============
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS off;

        include fastcgi_params;
        fastcgi_read_timeout 120;
        fastcgi_send_timeout 120;
    }

    #========== Security ============
    location ~ /\.ht {
        deny all;
    }

    #========== Static Files ============
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Optional: Enable Gzip compression for better performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss;
}
